apiVersion: v1
kind: Service
metadata:
  name: prometheus-longhorn
  namespace: default
spec:
  type: NodePort
  ports:
  - name: web
    nodePort: 30904
    port: 9090
    protocol: TCP
    targetPort: web
  selector:
    prometheus: longhorn
